### PR TITLE
Fix #2866: Build bazel for util/datetime

### LINKED ISSUE #2866: Create a BUILD.bazel file for the datetime package in the utility module
This task is part of the build system migration from Gradle to Bazel. 

## Prerequesites

- Make sure you are able to build Oppia using Bazel
- Follow the [Oppia Bazel Setup instructions](https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions) to setup Bazel and learn the terminology.
- Read the [Gradle Bazel Migration Best Practies and FAQ](https://github.com/oppia/oppia-android/wiki/Gradle--Bazel-Migration-Best-Practices-and-FAQ) for more context and see if there's an answer there to any question you have.

## Task

1. Create a BUILD.bazel file in

`src/main/java/org/oppia/android/util/datetime/`

2. Define a single kt_android_library

This library will have the single kotlin file as its srcs dependency and will also depend on parts of the system package of the utility module.

Figure out which deps dependencies you need to add and add them. This will also include third_party dependencies. See `third_party/versions.bzl` for the full list of third_party dependencies and use the minimal set required to build this library based on the imports.

The library should also have a single file in its resource_files field

`    resource_files = ["src/main/res/values/strings.xml"],`

Run
```
bazel build :all
```
inside the directory, to verify that the libraries build.

3. Add the directory to the MIGRATED_PROD_FILES of the module's root BUILD.bazel file

4. Set the appropriate visibility of the library and add the library to the list of deps dependencies in the targets that require the library

The visibility will depend on where the library is used. See useful links below to see a list of available visibilities. Use the most restrictive and relevant one that you can.

5. Clean up any unused deps dependencies

6. Verify that the app builds

## Useful links

- [BUILD.bazel files](https://github.com/oppia/oppia-android/search?q=filename%3ABUILD.bazel&type=code)
- [Visibilities](https://github.com/oppia/oppia-android/blob/76dc13dba3ad77aecd2218a5372949d6551f12fe/BUILD.bazel)
- [third_party dependencies](https://github.com/oppia/oppia-android/blob/a70d9b016f0d77dd30c4939041f82ea02ee28d1d/third_party/versions.bzl)

### PR DESCRIPTION
**Pull request by FareesHussain**
## Explanation

Fixes #2866 
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by FareesHussain** [comment]
@fsharpasharp Can you have a look at this error

```
ERROR: /home/farees/opensource/oppia-android/utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel:7:19: no such package 'utility/src/main/res/values/strings.xml': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.

```

File: utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")
+
+kt_android_library(
+    name = "date_time_util",
+    srcs = [
+        "DateTimeUtil.kt",
+    ],
+    manifest = "//utility/src/main/AndroidManifest.xml",
+    resource_files = ["//utility/src/main/res/values/strings.xml"],
```
Comment (fsharpasharp) [inline utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: Try only "src/main/res/values/strings.xml"

Comment (FareesHussain) [reply utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: @fsharpasharp 
```bash
farees@elementary-os:~/opensource/oppia-android/utility/src/main/java/org/oppia/android/util/datetime$ bazel build :all
ERROR: /home/farees/opensource/oppia-android/utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel:7:19: no such package 'utility/src/main/AndroidManifest.xml': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/farees/opensource/oppia-android/utility/src/main/AndroidManifest.xml and referenced by '//utility/src/main/java/org/oppia/android/util/datetime:date_time_util_base'
ERROR: Analysis of target '//utility/src/main/java/org/oppia/android/util/datetime:date_time_util_base' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.281s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 0 targets configured)
    currently loading: @kt_java_stub_template//file ... (2 packages)

```

Comment (FareesHussain) [reply utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: when I use `manifest = "src/main/AndroidManifest.xml"`

```bash
ERROR: /home/farees/opensource/oppia-android/utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel:7:19: Merging manifest for //utility/src/main/java/org/oppia/android/util/datetime:date_time_util_base failed: missing input file '//utility/src/main/java/org/oppia/android/util/datetime:src/main/AndroidManifest.xml'
ERROR: /home/farees/opensource/oppia-android/utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel:7:19 Merging manifest for //utility/src/main/java/org/oppia/android/util/datetime:date_time_util_base failed: 1 input file(s) do not exist
INFO: Elapsed time: 20.467s, Critical Path: 6.35s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

```

Comment (fsharpasharp) [reply utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: I'll take a closer look and get back to you by tomorrow.

Comment (BenHenning) [reply utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: Without ``//`` isn't the relative path based on ``//utility/src/main/java/org/oppia/android/util``? The manifest & resource files aren't under that directory.

Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: Note that we'll want to remove the manifest/resources from the top-level utility library as well to make sure we aren't duplicating the resources reference.

Can we actually move the manifest/resource files to be under datetime, or does that break Gradle?

**Review by BenHenning — COMMENTED** [review]
Thanks @FareesHussain! Left some thoughts.

File: utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel (hunk 1 above)
Comment (FareesHussain) [reply utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: From what I understand is that we need to exclude the strings.xml from the resources glob
https://github.com/oppia/oppia-android/blob/a714d1f55c8827760e6150db10b83f0e0853cbd1/utility/BUILD.bazel#L29

In that case, `strings.xml` is only used in the util/datetime we can remove this, will do this once I'm able to make a successful build

Comment (FareesHussain) [reply utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: > Without // isn't the relative path based on //utility/src/main/java/org/oppia/android/util? The manifest & resource files aren't under that directory.

I didn't get this. 
but for [AndroidManifest.xml](https://github.com/oppia/oppia-android/blob/develop/utility/src/main/AndroidManifest.xml) the relative path has to be `//utility/src/main/` right?

And I think we need to use `//` here as the AndroidManifest.xml is behind the util package

Just in case tried to build with `//utility/src/main/java/org/oppia/android/util` 
```bash
ERROR: /home/farees/opensource/oppia-android/utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel:7:19: no such package 'utility/src/main/java/org/oppia/android/util/AndroidManifest.xml': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/farees/opensource/oppia-android/utility/src/main/java/org/oppia/android/util/AndroidManifest.xml and referenced by '//utility/src/main/java/org/oppia/android/util/datetime:date_time_util_base'
ERROR: Analysis of target '//utility/src/main/java/org/oppia/android/util/datetime:date_time_util_base' failed; build aborted: Analysis failed
INFO: Elapsed time: 8.203s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 27 targets configured)

```

Comment (FareesHussain) [reply utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: Regarding moving manifest/res files under datetime

I think it's not a good practice as this alters the project architechture

And I did try to move the strings.xml to util/datetime and copied AndroidManifest.xm lto util/datetime when I build it gives the following error

```bash
ERROR: /home/farees/opensource/oppia-android/utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel:7:19: in resource_files attribute of android_library rule //utility/src/main/java/org/oppia/android/util/datetime:date_time_util_base: 'utility/src/main/java/org/oppia/android/util/datetime/strings.xml' is not in the expected resource directory structure of <resource directory>/{anim,animator,color,drawable,font,interpolator,layout,menu,mipmap,navigation,raw,transition,values,xml}/<file>. Since this rule was created by the macro 'kt_android_library', the error might have been caused by the macro implementation
ERROR: Analysis of target '//utility/src/main/java/org/oppia/android/util/datetime:date_time_util_kt' failed; build aborted: Analysis of target '//utility/src/main/java/org/oppia/android/util/datetime:date_time_util_base' failed
INFO: Elapsed time: 1.276s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (27 packages loaded, 731 targets configured)

```

**Comment by FareesHussain** [comment]
is there any way to declare a variable/target in the utility/BUILD.bazel and use it in the datetime/BUILD.bazel similar to the visibility package groups (Just a guess)

File: utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel (hunk 1 above)
Comment (fsharpasharp) [reply utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: Try copying the strings.xml to datetime/res/values/strings.xml

Comment (FareesHussain) [reply utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: @fsharpasharp How do I create a `res` package inside `datetime`

Comment (FareesHussain) [reply utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: and how do I make changes for `AndroidManifest.xml`

Comment (FareesHussain) [reply utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: I tried to create a package `res.values` and copied strings.xml here 
and as for AndroidManifest.xml I copied it to `util/datetime`

but how to make DateTimeUtil use the string resources i.e, from `util/datetime/res/values/strings.xml`

when I run it gives the following error

```bash
ERROR: /home/farees/opensource/oppia-android/utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel:7:19: KotlinCompile //utility/src/main/java/org/oppia/android/util/datetime:date_time_util_kt { kt: 1, java: 0, srcjars: 0 } for k8 failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/builder ... (remaining 1 argument(s) skipped)
utility/src/main/java/org/oppia/android/util/datetime/DateTimeUtil.kt:4:31: error: unresolved reference: R
import org.oppia.android.util.R
                              ^
Compilation failure: compile phase failed:
/home/farees/.cache/bazel/_bazel_farees/be6e0c0a55083b3b0484cd1169352d74/execroot/__main__/utility/src/main/java/org/oppia/android/util/datetime/DateTimeUtil.kt:4:31: error: unresolved reference: R
import org.oppia.android.util.R
                              ^
INFO: Elapsed time: 2.625s, Critical Path: 2.08s
INFO: 2 processes: 2 internal.

```

Comment (BenHenning) [reply utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel]: Hmm. It actually is preferred practice in Bazel projects to have resources as close to the location as possible, but the R file import bit is going to be a problem.

@fsharpasharp it might make more sense for us to wait to modularize resources until after all the build packages are done, and after we remove Gradle since it probably isn't going to like that. It might mean that we need to introduce explicit resource libraries at the top level to reference everywhere, and I'm not sure how that's going to work with databinding in app module yet. WDYT?

**Comment by BenHenning** [comment]
What sort of variable are you thinking to share @FareesHussain? I think what you're looking for is possible, but I don't fully understand what you're trying to solve per that question.

**Comment by FareesHussain** [comment]
> What sort of variable are you thinking to share @FareesHussain? I think what you're looking for is possible, but I don't fully understand what you're trying to solve per that question.

What I meant is similar to 
https://github.com/oppia/oppia-android/blob/15a7450e09795b75f48f094fc8152379e30c0219/BUILD.bazel#L6

here as we are unable to directly refer to the `AndroidManifest.xml` or `string.xml` from `util/datetime` package
and we could use it something like 
```
 manifest = "//utility:manifest",
 resource_files = ["//utility:strings"],
```

I'm not particular if this would exactly work here 
this can also be similar to the above error https://github.com/oppia/oppia-android/pull/2868#issuecomment-794317144

**Comment by fsharpasharp** [comment]
> > What sort of variable are you thinking to share @FareesHussain? I think what you're looking for is possible, but I don't fully understand what you're trying to solve per that question.
> 
> What I meant is similar to
> https://github.com/oppia/oppia-android/blob/15a7450e09795b75f48f094fc8152379e30c0219/BUILD.bazel#L6
> 
> here as we are unable to directly refer to the `AndroidManifest.xml` or `string.xml` from `util/datetime` package
> and we could use it something like
> 
> ```
>  manifest = "//utility:manifest",
>  resource_files = ["//utility:strings"],
> ```
> 
> I'm not particular if this would exactly work here
> this can also be similar to the above error [#2868 (comment)](https://github.com/oppia/oppia-android/pull/2868#issuecomment-794317144)

We can use filegroups for this

https://docs.bazel.build/versions/master/be/general.html#filegroup

**Comment by FareesHussain** [comment]
@fsharpasharp here I used file_groups it did avoid the package error for manifest and resources but I get the import error for `R`
https://github.com/oppia/oppia-android/blob/41ebb8693cf6d882d617081a1f99e843e916e591/utility/src/main/java/org/oppia/android/util/datetime/DateTimeUtil.kt#L4

```
ERROR: /home/farees/opensource/oppia-android/utility/src/main/java/org/oppia/android/util/datetime/BUILD.bazel:7:19: KotlinCompile //utility/src/main/java/org/oppia/android/util/datetime:date_time_util_kt { kt: 1, java: 0, srcjars: 0 } for k8 failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/builder ... (remaining 1 argument(s) skipped)
utility/src/main/java/org/oppia/android/util/datetime/DateTimeUtil.kt:4:31: error: unresolved reference: R
import org.oppia.android.util.R
                              ^
Compilation failure: compile phase failed:
/home/farees/.cache/bazel/_bazel_farees/be6e0c0a55083b3b0484cd1169352d74/execroot/__main__/utility/src/main/java/org/oppia/android/util/datetime/DateTimeUtil.kt:4:31: error: unresolved reference: R
import org.oppia.android.util.R
                              ^
INFO: Elapsed time: 23.286s, Critical Path: 11.67s
INFO: 6 processes: 2 internal, 4 linux-sandbox.
FAILED: Build did NOT complete successfully

```

I guess this is similar to https://github.com/oppia/oppia-android/pull/2868#discussion_r591918000

**Comment by FareesHussain** [comment]
@BenHenning not sure why this shows an error related to `dimes.xml` do I have to add a BUILD.bazel for `util/parser` too ? 

```
"""
General purposes utilities for Android accessibility checking.
"""

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")

kt_android_library(
    name = "date_time_util",
    srcs = [
        "DateTimeUtil.kt",
    ],
    visibility = ["//:oppia_api_visibility"],
    deps = [
        "//third_party:javax_inject_javax_inject",
        "//utility:strings",
        "//utility/src/main/java/org/oppia/android/util/system:oppia_clock",
    ],
)

```

File: utility/BUILD.bazel [hunk 2]
```diff
@@ -17,6 +17,22 @@ MIGRATED_PROD_FILES = glob([
...
+filegroup(
+    name = "manifest",
+    srcs = [
+        "src/main/AndroidManifest.xml",
+    ],
+    visibility = ["//visibility:public"],
+)
+
+android_library(
+    name = "strings",
```
Comment (BenHenning) [inline utility/BUILD.bazel]: Could we export all resources instead of just strings? That would use a ``glob`` below for the ``resource_files``, and this should be called "resources".

Please also remove the resource files & manifest reference from "utility" below. If it still needs resources then it should add a dependency on this, instead.

File: utility/BUILD.bazel [hunk 3]
```diff
@@ -17,6 +17,22 @@ MIGRATED_PROD_FILES = glob([
     "src/main/java/org/oppia/android/util/system/*.kt",
 ])
 
+filegroup(
+    name = "manifest",
```
Comment (BenHenning) [inline utility/BUILD.bazel]: Is this still needed? Suggest removing it.

**Review by BenHenning — COMMENTED** [review]
Thanks @FareesHussain! Left a few more thoughts.

Regarding your error with dimens, what exactly is the error? Can you add a Gist log of it?

**Comment by FareesHussain** [comment]
@BenHenning sorry for the delay, I copied the wrong one here https://github.com/oppia/oppia-android/pull/2868#issuecomment-797096181

```
ERROR: /home/runner/work/oppia-android/oppia-android/utility/BUILD.bazel:37:19: KotlinCompile //utility:utility_kt { kt: 56, java: 0, srcjars: 0 } for armeabi-v7a failed (Exit 1)
utility/src/main/java/org/oppia/android/util/parser/CustomBulletSpan.kt:24:64: error: unresolved reference: dimen
  private val bulletRadius = resources.getDimensionPixelSize(R.dimen.bullet_radius)
                                                               ^
utility/src/main/java/org/oppia/android/util/parser/CustomBulletSpan.kt:25:60: error: unresolved reference: dimen
  private val gapWidth = resources.getDimensionPixelSize(R.dimen.bullet_gap_width)
                                                           ^
utility/src/main/java/org/oppia/android/util/parser/CustomBulletSpan.kt:26:59: error: unresolved reference: dimen
  private val yOffset = resources.getDimensionPixelSize(R.dimen.bullet_y_offset)
                                                          ^
utility/src/main/java/org/oppia/android/util/parser/CustomBulletSpan.kt:28:71: error: unresolved reference: dimen
  private val spacingBeforeBullet = resources.getDimensionPixelSize(R.dimen.spacing_before_bullet)
                                                                      ^
utility/src/main/java/org/oppia/android/util/parser/CustomBulletSpan.kt:30:69: error: unresolved reference: dimen
  private val spacingBeforeText = resources.getDimensionPixelSize(R.dimen.spacing_before_text)
                                                                    ^
utility/src/main/java/org/oppia/android/util/parser/UrlImageParser.kt:89:76: error: unresolved reference: dimen
          val minimumImageSize = context.resources.getDimensionPixelSize(R.dimen.minimum_image_size)
                                                                           ^
utility/src/main/java/org/oppia/android/util/parser/UrlImageParser.kt:106:55: error: unresolved reference: dimen
            context.resources.getDimensionPixelSize(R.dimen.maximum_content_item_padding)
                                                      ^
Compilation failure: compile phase failed:
/home/runner/.cache/bazel/_bazel_runner/ef69b31fa14ea8341d6589b0a8832bdd/execroot/__main__/utility/src/main/java/org/oppia/android/util/parser/CustomBulletSpan.kt:24:64: error: unresolved reference: dimen
  private val bulletRadius = resources.getDimensionPixelSize(R.dimen.bullet_radius)
                                                               ^
/home/runner/.cache/bazel/_bazel_runner/ef69b31fa14ea8341d6589b0a8832bdd/execroot/__main__/utility/src/main/java/org/oppia/android/util/parser/CustomBulletSpan.kt:25:60: error: unresolved reference: dimen
  private val gapWidth = resources.getDimensionPixelSize(R.dimen.bullet_gap_width)
                                                           ^
/home/runner/.cache/bazel/_bazel_runner/ef69b31fa14ea8341d6589b0a8832bdd/execroot/__main__/utility/src/main/java/org/oppia/android/util/parser/CustomBulletSpan.kt:26:59: error: unresolved reference: dimen
  private val yOffset = resources.getDimensionPixelSize(R.dimen.bullet_y_offset)
                                                          ^
/home/runner/.cache/bazel/_bazel_runner/ef69b31fa14ea8341d6589b0a8832bdd/execroot/__main__/utility/src/main/java/org/oppia/android/util/parser/CustomBulletSpan.kt:28:71: error: unresolved reference: dimen
  private val spacingBeforeBullet = resources.getDimensionPixelSize(R.dimen.spacing_before_bullet)
                                                                      ^
/home/runner/.cache/bazel/_bazel_runner/ef69b31fa14ea8341d6589b0a8832bdd/execroot/__main__/utility/src/main/java/org/oppia/android/util/parser/CustomBulletSpan.kt:30:69: error: unresolved reference: dimen
  private val spacingBeforeText = resources.getDimensionPixelSize(R.dimen.spacing_before_text)
                                                                    ^
/home/runner/.cache/bazel/_bazel_runner/ef69b31fa14ea8341d6589b0a8832bdd/execroot/__main__/utility/src/main/java/org/oppia/android/util/parser/UrlImageParser.kt:89:76: error: unresolved reference: dimen
          val minimumImageSize = context.resources.getDimensionPixelSize(R.dimen.minimum_image_size)
                                                                           ^
/home/runner/.cache/bazel/_bazel_runner/ef69b31fa14ea8341d6589b0a8832bdd/execroot/__main__/utility/src/main/java/org/oppia/android/util/parser/UrlImageParser.kt:106:55: error: unresolved reference: dimen
            context.resources.getDimensionPixelSize(R.dimen.maximum_content_item_padding)
                                                      ^
Target //:oppia failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 675.304s, Critical Path: 43.08s
INFO: 1624 processes: 1459 linux-sandbox, 165 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
Error: Process completed with exit code 1.
```

File: utility/BUILD.bazel (hunk 3 above)
Comment (FareesHussain) [reply utility/BUILD.bazel]: Done

File: utility/BUILD.bazel (hunk 2 above)
Comment (FareesHussain) [reply utility/BUILD.bazel]: done

**Comment by FareesHussain** [comment]
https://gist.github.com/FareesHussain/90bb0e951c3526298db9fec2dbb348bc

Created a gist for the errors related to dimens.xml

**Comment by FareesHussain** [comment]
Now I get the following error when I run `bazel build //:oppia`

```
ERROR: /home/farees/opensource/oppia-android/app/BUILD.bazel:551:19: Building app/libview_models_base.jar (1 source file, 1 source jar) and running annotation processors (ComponentProcessor, ProcessDataBinding) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
bazel-out/android-armeabi-v7a-fastbuild/bin/app/databinding/view_models_base/DataBindingInfo.java:3: error: cannot find symbol
import android.databinding.BindingBuildInfo;
                          ^
  symbol:   class BindingBuildInfo
  location: package android.databinding
bazel-out/android-armeabi-v7a-fastbuild/bin/app/databinding/view_models_base/DataBindingInfo.java:10: error: cannot find symbol
@BindingBuildInfo(
 ^
  symbol: class BindingBuildInfo
Target //:oppia failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.921s, Critical Path: 1.45s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully

```

**Comment by FareesHussain** [comment]
@BenHenning @fsharpasharp PTAL

**Review by BenHenning — APPROVED** [review]
Thanks @FareesHussain! This LGTM. The Bazel CI failure seems to be due to #2844.

**Comment by FareesHussain** [comment]
@fsharpasharp PTAL

**Review by fsharpasharp — APPROVED** [review]
Nice! Thanks for solving the resources issue with its ambiguity.

**Comment by BenHenning** [comment]
Thanks @FareesHussain!
